version: '3'
services:
  db:
    image: mysql:8.0
    container_name: admin_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: admin_db
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: admin_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  web:
    build: .
    container_name: admin_app
    command: gunicorn --bind 0.0.0.0:8080 hanum_ad.wsgi:application
    environment:
      - DEBUG=0
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
