# Generated by Django 5.1.1 on 2024-09-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0005_delete_articlecomments_delete_articles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComments',
            fields=[
                ('id', models.BigAutoField(db_comment='��� ID', primary_key=True, serialize=False)),
                ('authorid', models.PositiveBigIntegerField(db_column='authorId', db_comment='�ۼ��� ID')),
                ('isanonymous', models.IntegerField(db_column='isAnonymous', db_comment='�\u0378� ����')),
                ('content', models.CharField(blank=True, db_comment='��� ����', max_length=1000, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt', db_comment='��� ���� ��¥')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', db_comment='��� ���� ��¥', null=True)),
                ('deletedat', models.DateTimeField(blank=True, db_column='deletedAt', db_comment='��� ���� ��¥', null=True)),
            ],
            options={
                'db_table': 'article_comments',
                'db_table_comment': '�Խñ� ���, ��� ���̺�',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(db_comment='�Խñ� ID', primary_key=True, serialize=False)),
                ('authorid', models.PositiveBigIntegerField(db_column='authorId', db_comment='�ۼ��� ID')),
                ('authernickname', models.CharField(blank=True, db_column='autherNickname', db_comment='�\u0378� �ۼ��� �̸�', max_length=50, null=True)),
                ('isanonymous', models.IntegerField(db_column='isAnonymous', db_comment='�\u0378� ����')),
                ('scope', models.PositiveIntegerField(blank=True, db_comment='���� ����', null=True)),
                ('cluster', models.PositiveIntegerField(blank=True, db_comment='���� �\u05f7�', null=True)),
                ('content', models.CharField(db_comment='�Խñ� ����', max_length=10000)),
                ('createdat', models.DateTimeField(db_column='createdAt', db_comment='�Խñ� ���� ��¥')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', db_comment='�Խñ� ���� ��¥', null=True)),
                ('deletedat', models.DateTimeField(blank=True, db_column='deletedAt', db_comment='�Խñ� ���� ��¥', null=True)),
            ],
            options={
                'db_table': 'articles',
                'db_table_comment': '�Խñ� ���̺�',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserBlocks',
            fields=[
                ('id', models.BigAutoField(db_comment='����� ���� ID', primary_key=True, serialize=False)),
                ('userid', models.PositiveBigIntegerField(db_column='userId', db_comment='������ ����� ID')),
                ('targetid', models.PositiveBigIntegerField(db_column='targetId', db_comment='���� ��� ����� ID')),
                ('createdat', models.DateTimeField(db_column='createdAt', db_comment='������ ��¥')),
            ],
            options={
                'db_table': 'user_blocks',
                'db_table_comment': '����� ���� ���̺�',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=5)),
                ('profile', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
