# Generated by Django 5.1.1 on 2024-09-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleComments',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='UserBlocks',
        ),
    ]
